// src/components/sections/Home.tsx
import { useState, useEffect, type ReactNode } from 'react'

interface HomeProps {
  navigation?: ReactNode
}

export default function Home({ navigation }: HomeProps) {
  const phoneNumber = '+48123123123'
  const [copied, setCopied] = useState(false)
  const [isMobile, setIsMobile] = useState(false)

  useEffect(() => {
    setIsMobile(/Android|iPhone|iPad|iPod/i.test(navigator.userAgent))
  }, [])

  function copyPhoneNumber() {
    navigator.clipboard.writeText('+48 123 123 123')
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="relative flex flex-col items-center justify-evenly w-full h-full px-4 gap-4 overflow-visible">
      {/* Decorative gradient orbs */}
      <div className="absolute top-[-15%] left-[-5%] w-[500px] h-[500px] bg-sky-500/10 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-[-15%] right-[-5%] w-[400px] h-[400px] bg-indigo-500/8 rounded-full blur-[120px] pointer-events-none" />

      <img
        className="relative w-[200px] h-[200px] sm:w-[380px] sm:h-[380px] drop-shadow-[0_0_60px_rgba(56,189,248,0.15)]"
        src="/medical_bed.png"
        alt="Łóżka Rehabilitacyjne"
      />

      <div className="flex flex-col items-center gap-2 text-center">
        <h1 className="text-4xl sm:text-8xl font-extrabold bg-gradient-to-r from-white via-sky-200 to-sky-400 bg-clip-text text-transparent">
          Łukasz Skrond
        </h1>
        <p className="text-lg sm:text-xl text-gray-400 max-w-xl">
          Sprzedaż łóżek rehabilitacyjnych do opieki długoterminowej
        </p>
      </div>

      <div className="flex flex-col items-center gap-2 text-center">
        {isMobile ? (
          <>
            <p className="text-2xl text-gray-300">Zadzwoń:</p>
            <a
              href={`tel:${phoneNumber}`}
              className="font-bold text-3xl sm:text-4xl text-sky-400 hover:text-sky-300 transition-colors"
            >
              +48 123 123 123
            </a>
          </>
        ) : (
          <>
            <p className="text-sm text-gray-500">(Kliknij numer telefonu aby skopiować do schowka!)</p>
            <button
              onClick={copyPhoneNumber}
              className="font-bold cursor-pointer text-3xl sm:text-5xl text-white hover:text-sky-400 focus:outline-none transition-colors duration-200"
            >
              +48 123 123 123
            </button>
            {copied && (
              <span className="text-sm text-emerald-400 animate-fade-in">
                <i className="pi pi-check mr-1" />Skopiowano do schowka!
              </span>
            )}
          </>
        )}
      </div>

      {navigation}
    </div>
  )
}

// src/components/sections/Home.vue
<template>
  <div class="flex flex-col items-center justify-evenly w-full h-full px-4 gap-4">
    <img class="sm:w-[500px] sm:h-[500px]" src="/logo.png" alt="Logo" />

    <div class="flex flex-col items-center gap-2 text-center">
      <template v-if="isMobile">
        <p class="text-3xl">Zadzwoń:</p>
        <a
          :href="`tel:${phoneNumber}`"
          class="font-bold sm:text-4xl text-3xl text-blue-600 hover:underline"
        >
          +48 123 123 123
        </a>
      </template>
      <template v-else>
        <p class="text-sm">(Kliknij numer telefonu aby skopiować do schowka!)</p>
        <button
          @click="copyPhoneNumber"
          class="font-bold cursor-pointer sm:text-4xl text-3xl text-white hover:text-blue-600 focus:outline-none"
        >
          +48 123 123 123
        </button>
        <span class="text-sm text-green-600" v-if="copied">Skopiowano do schowka!</span>
      </template>
    </div>

    <slot name="navigation" />
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'

const phoneNumber = '+48123123123'
const copied = ref(false)
const isMobile = ref(false)

onMounted(() => {
  isMobile.value = /Android|iPhone|iPad|iPod/i.test(navigator.userAgent)
})

function copyPhoneNumber() {
  navigator.clipboard.writeText('+48 123 123 123')
  copied.value = true
  setTimeout(() => (copied.value = false), 2000)
}
</script>
